### ISSUE TITLE
Add react project to public folder for admin website

### ISSUE THREAD

**Issue by CesarJimenezVilleda02** [Roberto-Ruiz-Obregon/BackEnd#3]

**Comment by Luis-ERP** [comment]
Eso es otra cosa que iba a preguntar, si va a ser una pagina estatica no seria mas facil hacer otro repo y solo subirlo con github pages?

**Comment by Luis-ERP** [comment]
No sería mejor hacer un repo por separado y ya solo cuando hagamos el build agregarlo a la carpeta static? o en todo caso dejarlo en su mismo repo y usar github pages, al final es una página estática

**Comment by CesarJimenezVilleda02** [comment]
Ahhh, pues si, mejor vamonos por lo practico. Digo, en mi opinion no esta tan dificil servirlo del express pero para tener mejor control de los issues de admin y esas cosas mejor hay que moverlo.

**Comment by felix-rojas** [comment]
Y pues está gratis y sencillo
o sea si está bonito así y en caso de tener que pasarlo con react o así pues ya tenemos un template base
________________________________

**Comment by CesarJimenezVilleda02** [comment]
Vale, ejerzo mi poder como SCRUM MASTER y cierro este issue.
